---
title: "CraniumData"
author: "Peyton Hall"
date: "07/26/2024"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load necessary libraries}
library(readxl)
library(ggplot2)
```

```{r Read the excel file}
pbio_1001071_s003 <- read_excel("~/Desktop/CraniaAmericana/pbio.1001071.s003.xls")
pbio_1001071_s003
# Rename columns if necessary (example shown with column names from the image)
colnames(pbio_1001071_s003) <- c("Specimen#", "Affiliation", "Plate", "FA",
                                 "IC", "Deformed", "MortonGroup")
# Keep only the relevant columns
cranial_data <- pbio_1001071_s003[, c("Affiliation", "IC", "MortonGroup")]
# Print the cleaned column names to verify
print(colnames(cranial_data))
```

```{r Graph the data}
# Ensure the IC column is numeric
cranial_data$IC <- as.numeric(cranial_data$IC)
# Filter out "Affiliation" and "NA" from the Affiliation column
cranial_data_filtered <- cranial_data[!cranial_data$Affiliation %in% 
                                        c("Affiliation", NA), ]
ggplot(cranial_data_filtered, aes(x = Affiliation, y = IC)) +
  geom_bar(stat = "identity", position = "dodge", 
           fill = "gray", color = "black") +
  labs(title = "Cranial Capacity by Race",
       x = "Affiliation",
       y = "Cranial Capacity (Cubic Inches)",
       caption = "Source: Samuel George Morton (1839) Crania Americana; or, 
       A Comparative View of the Skulls of Various Aboriginal Nations of North and South America") +
  scale_y_continuous(breaks = seq(0, 100, by = 5)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 8),
        axis.text.y = element_text(size = 8),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0.5, size = 8))
```

